version: "3.8"
services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    volumes:
      - ../awesomeapp:/home/awesomeapp
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
  bundle_cache: